FROM vanjoge/mediasoup-demo AS stage-one

WORKDIR /app

COPY . .

RUN set -ex \
  && apt-get update \
  && apt-get install -y git \
  && npm install \
  && apt-get  autoremove -y git \
  && rm -rf /var/lib/apt/lists/*

CMD ["npm", "start"]
