FROM node:10-slim AS stage-one

# Install DEB dependencies and others.
RUN \
	set -x \
	&& apt-get update \
	&& apt-get install -y net-tools build-essential valgrind

WORKDIR /server

COPY package.json .
RUN npm install
COPY server.js .
#COPY config.js .
COPY lib lib
#COPY certs certs

CMD ["node", "/server/server.js"]
