FROM node:10-slim AS stage-one

WORKDIR /server

COPY package.json .

# Install DEB dependencies and others.
RUN set -ex \
  && apt-get update \
  && apt-get install -y make gcc g++ python git \
  && npm install \
  && apt-get  autoremove -y git \
  && rm -rf /var/lib/apt/lists/*

COPY server.js .
COPY lib lib

CMD ["node", "/server/server.js"]
